name: 'Rust Musl'
description: 'Adds Musl capabilities for rust compilation target'
author: 'Daniel Stahl <danstahl1138@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'orange'